### ISSUE TITLE
Add Additional Animals

### ISSUE THREAD

**Issue by Duder-onomy** [Duder-onomy/Dinosaurs#3]
Program should, instead of going right into the Dinosaur Direcotory, It will seach an "Animals Directory"

The program will display, after you start it, a list of all the Animal folders in the the Animal directory:  such as
    "What Animals do you want to see?"
    [0] - Cats
    [1] - Dinosaurs
    [2] - Dogs

Then once selected, it will drop down into the main program to list then display the animals. 

This will probably require we refactor Dinosaur.rb into something like Animal.rb
Then add additional layer to the AsciiArt.rb to find the animal folders, display and select them, then pass the selected parent directory to the Animals.rb so that it knows which folder it should be selecting from.

**Comment by zeisler** [comment]
I think that would be neat but first what is this point of this app? Is it to display cool Dino's or just load text in from a file? Adding more features that completely change it, I'm not sure if its that helpful for learning or if we should only improve the basic concept and then move on to our next idea and make another app.

**Comment by Duder-onomy** [comment]
understood. I dont think it would be productive for you if you allready know. 
I think it would be a good idea for me as I would like to be able to pull off the file searching and hashing w/o your and Shane's guidance. All the applications I have made up until now have never used a file system in such a simple way. 
Anyways, those are just my thoughts. I can make a new repo that is a more "general" app that justs lists and diaplays folders and directories. For my own practice. 

Greg

**Comment by zeisler** [comment]
I think you should make the thing from scratch without our help and see how you do.

**Comment by ShaneDelmore** [comment]
Do it, I say 100% helpful.  Nothing is as core to the software industry as changing requirements.  Someone asks you to make a dinosaur projector, then next week they say "I meant an animal projector, I just used dinosaur as one example".  Then next week they say "I meant object projector, animals were just one cool thing you could show".  You keep refactoring, making your code more and more abstract until it does everything they need. Or you die.

**Comment by Duder-onomy** [comment]
Lol. 
Thanks dudes. 
Always helpful as usual.  
All the applications I have written for clients over the last 6 years of freelancing were always super specific / complicated use cases...never needed to be refactored or revisited by the nature of the requirements and the skill of the users.  We are all in the class for different reasons, my big one is agile, that and generalizing my apps so I can reuse the code.  So it would be good practice for me thrice fold. 
Writing the entire code base from scratch would be helpful, there was at least 1 topic in there that I had never seen b4…the rest would just be good practice doing it in Ruby. 
  I have committed myself to producing at least 2 significant apps each week in addition to the HW. So, I will give myself another 24 hours on this project and no more. 

Greg
